- backend/db.js
- backend/package-lock.json
> Issue#7 put_exam_data_in_database

- backend/app.js
> Issue#10 set up main web page URL

- frontend/geocoding.js
- frontend/main.css
- frontend/main.html
> Issue#6 Connect server with client And Make map feature

- backend/lib/findRoute/byDriving.js
> Issue#17 Improve driving function output

- backend/lib/findRoute/byDriving.js
- backend/router/v1/findRoute.js
> Issue#22 hot fix in driving route finding function

- backend/app.js
- backend/router/v1/findRoute.js
> Issue#20 make rspone json format

- src/frontend/config/Api.js
- src/frontend/config/Api_template.js
> Issue#27-bug-fix-on-main-webpage-about-API

- src/backend/.gitignore
- src/backend/location_candidates_template.json
> Issue#31-add-location-candidates-file

- src/backend/lib/findRoute/find_loc_candidates.js
> Issue#33-make-location-candidate-finder

- src/backend/app.js
- src/backend/config/server_config_template.json
- src/backend/lib/findRoute/bySubway.js
- src/backend/lib/findRoute/find_loc_candidates.js
- src/backend/router/index.js
- src/backend/router/v1/findRoute.js
> Issue#41-send-coordinates-and-get-candidates

- src/backend/db.js
- src/backend/lib/findRoute/bySubway.js
- src/backend/router/v1/findRoute.js
> Issue#44 sort candidate results

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/public/index.html
- src/frontend/src/App.js
#47 
Apply material-ui/core, material-icons
> Issue#47-Apply-material-ui

- src/backend/router/v1/findRoute.js
- src/frontend/package-lock.json
- src/frontend/src/App.js
> Issue#57 Fix request data type

- src/frontend/src/App.js
#56 
Improved UI of input box
Improved UI of result box
> Issue#56-Improve-UI-for-input-and-result-box

- src/backend/router/v1/findRoute.js
> Issue#49 Improve result sorting algorithm

- src/backend/router/v1/findRoute.js
> Issue#61 Change result sorting criterion

- src/backend/app.js
- src/backend/lib/findRoute/byPublic.js
- src/backend/package-lock.json
- src/backend/package.json
- src/backend/router/v1/findRoute.js
> Issue#68 Add pedestrian route in public transportation

- src/frontend/src/App.js
- src/frontend/src/FindBox.js
- src/frontend/src/Map.js
> Issue#67 show result markers on map

- src/frontend/src/App.js
- src/frontend/src/FindBox.js
> Issue#70-Improve-result-box-ui-and-remove-button

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/FindBox.js
> Issue#80-Make scroll bar in find box and Add icon for select location

- src/backend/lib/findRoute/find_loc_candidates.js
> Issue#45 Improve candidate search algorithm

- src/backend/lib/findRoute/byPublic.js
> Issue#83 add walk as a way in travel info

- src/frontend/src/FindBox.js
> Issue#85 add transportation icon and place on top the button

- src/frontend/src/FindBox.js
> Issue#91-scrollbar-bug-fix

- src/frontend/src/App.js
- src/frontend/src/rwd.css
> Issue#100 change responsive breakpoints and share button

- src/backend/database/README.md
- src/backend/database/place_crawler.py
- src/backend/database/requirements.txt
> Issue#105 add caption crawling

- src/backend/lib/findRoute/candidatesWithUserData.js
- src/backend/lib/findRoute/candidatesWithUserdatas.js
- src/backend/lib/meeting/makeMeeting.js
- src/backend/models/Meeting.js
- src/backend/models/Result.js
- src/backend/models/index.js
- src/backend/router/v2/findRoute.js
> Issue#110 make resultDB and function

- src/frontend/src/FindBox.js
- src/frontend/src/Map.js
- src/frontend/src/rwd.css
> Issue#114 Fix the scroll bar and make GPS icon in SearchBox

- src/backend/database/place_crawler.py
> Issue#116-Change-crawling-sequence

- src/frontend/src/rwd.css
> Issue#118 Final change of responsive breakpoints

- src/frontend/src/MakeRoom.css
- src/frontend/src/MakeRoom.js
- src/frontend/src/PrivateRoom.css
- src/frontend/src/PrivateRoom.js
> Issue#119-Add MakeRoom and PrivateRoom

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/index.js
- src/frontend/src/v2/App.js
- src/frontend/src/v2/MakeRoom.js
- src/frontend/src/v2/Map.js
- src/frontend/src/v2/Meeting.js
- src/frontend/src/v2/PrivateRoom.js
> Issue#125 make frontend router

- src/backend/.gitignore
- src/backend/database/README.md
- src/backend/database/place_crawler.py
> Issue#126 enhance fetching sequence

- src/backend/db.js
- src/backend/models/CandidateLocs.js
- src/backend/models/CandidateVoting.js
- src/backend/models/index.js
- src/backend/router/index.js
- src/backend/router/v2/voting.js
> add voting function using meeting name

- src/backend/database/place_crawler.py
> Issue#134 Crawler Minor Refactoring

- src/frontend/public/index.html
- src/frontend/src/v2/App.js
- src/frontend/src/v2/Map.js
- src/frontend/src/v2/Meeting.js
- src/frontend/src/v2/PrivateRoom.js
> Issue#133 Create a Share To Kakao Talk function

- src/backend/config/API_KEY_template.json
- src/backend/database/place_sorter.py
> Issue#137 Sort candidate place result

- src/frontend/src/v2/ResultRoom.css
- src/frontend/src/v2/ResultRoom.js
#139 
1) Make and push ResultRoom.js. And it will show result of room.
2) also make ResultRoom.css.
> Issue#139-Add result box. 

- src/frontend/src/v2/Map.js
- src/frontend/src/v2/Meeting.js
- src/frontend/src/v2/PrivateRoom.css
- src/frontend/src/v2/PrivateRoom.js
- src/frontend/src/v2/rwd.css
> Issue#143 UI alignment and change submit list and add checkbox

- src/backend/db.js
- src/backend/lib/findRoute/candidatesWithUserData.js
- src/backend/lib/meeting/findMeetingData.js
- src/backend/lib/meeting/makeMeetingUser.js
- src/backend/models/CandidateLocs.js
- src/backend/models/MeetingUser.js
- src/backend/router/v2/findRoute.js
- src/backend/router/v2/meeting.js
- src/frontend/src/v2/Meeting.js
- src/frontend/src/v2/PrivateRoom.js
- src/frontend/src/v2/ResultRoom.js
> Issue128-find-result-from-meeting-user-db

- src/backend/router/v2/voting.js
> voting function using token

- src/frontend/src/v2/Meeting.js
> Issue#150 name input error

- src/frontend/src/v2/PrivateRoom.js
- src/frontend/src/v2/ResultRoom.css
- src/frontend/src/v2/ResultRoom.js
> Issue#157-Make-submit-status-and-checkbox

- src/frontend/src/v2/MakeRoom.js
- src/frontend/src/v2/PrivateRoom.js
- src/frontend/src/v2/ResultRoom.js
- src/frontend/src/v2/rwd.css
> Issue#161-Fix the mobile ui and scroll bar

- src/backend/lib/meeting/findMeetingData.js
> sending result including 'vote' value

- src/frontend/src/v2/MakeRoom.js
- src/frontend/src/v2/PrivateRoom.css
- src/frontend/src/v2/PrivateRoom.js
- src/frontend/src/v2/ResultRoom.css
#168 
Limit MakeRoom input number more than 1 and Limit submit number <= PrivateRoom user number
> Issue#168-Limit-MakeRoom-input-number-and-PrivateRoom-user-number

- src/frontend/src/v2/PrivateRoom.js
#165 
참여자의 절반이상이 출발위치를 입력하지 않았다면 결과를 보여주지 않습니다.
> cant use result button when majority dont submit starting point

- src/frontend/src/v2/Map.js
- src/frontend/src/v2/Meeting.js
- src/frontend/src/v2/ResultRoom.js
> click marker and show result

- src/frontend/src/v2/PrivateRoom.css
- src/frontend/src/v2/PrivateRoom.js
- src/frontend/src/v2/ResultRoom.css
- src/frontend/src/v2/ResultRoom.js
- src/frontend/src/v2/rwd.css
> Issue#184 Extension the scroll range

- src/frontend/package.json
- src/frontend/src/v2/Meeting.css
- src/frontend/src/v2/Meeting.js
- src/frontend/src/v2/PrivateRoom.css
- src/frontend/src/v2/ResultRoom.css
- src/frontend/src/v2/ResultRoom.js
> Issue#189-Redesign resultroom

- src/backend/database/rate_candidate.py
> Issue#191 create rating value

- src/frontend/src/v2/Meeting.js
- src/frontend/src/v2/rwd.css
> Issue#199-Fix the mobile touch scroll bubble

- src/frontend/src/index.js
- src/frontend/src/v2/App.js
- src/frontend/src/v2/Meeting.js
- src/frontend/src/v2/ResultRoom.css
- src/frontend/src/v2/rwd.css
> Bugfix in mobile

- src/backend/db_dummy_rating.js
- src/backend/db_rating_update.js
- src/backend/lib/findRoute/candidatesWithUserData.js
- src/frontend/src/v2/Meeting.js
> Issue#202-create-sort-function-by-rating

- src/frontend/src/v2/Meeting.css
- src/frontend/src/v2/Meeting.js
- src/frontend/src/v2/PrivateRoom.css
- src/frontend/src/v2/PrivateRoom.js
> Issue#207-Restyle

- src/frontend/src/v2/ResultRoom.css
- src/frontend/src/v2/ResultRoom.js
> Issue#211 Fix the scrollHeight and move the votebox

- src/frontend/src/v2/MakeRoom.js
> Issue#219-Modify-API-URL

- src/frontend/src/v2/PrivateRoom.css
- src/frontend/src/v2/PrivateRoom.js
- src/frontend/src/v2/rwd.css
> Issue#224 fix button position

- src/frontend/src/v2/Map.js
- src/frontend/src/v2/PrivateRoom.js
- src/frontend/src/v2/rwd.css
> Issue#233 maybe last bugfix

- src/frontend/src/v2/Meeting.css
- src/frontend/src/v2/Meeting.js
> Issue#235-Fix room name space

- src/frontend/src/v2/rwd.css
> Issue#237-Change mobile initial display

- src/frontend/src/v2/Map.css
> Issue#240-Bugfix info window

- src/backend/package-lock.json
- src/backend/package.json
> Issue#242 update dependency

- README.md
- index.md
- src/backend/.gitignore
- src/backend/location_candidates.json
- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/v1/App.js
- src/frontend/src/v2/Map.js
- src/frontend/src/v2/Meeting.js
> Issue#244 Modify APIs
